---
sudo: required

services:
  - docker

language: bash

notifications:
    slack: seleniumhq:Kx5MB7T51SPMpbBMYfvxNW4q

before_install:
  - docker info
  - VERSION="$TRAVIS_BRANCH" make build
  - docker build -t test:local ./Test

script:
  - VERSION="$TRAVIS_BRANCH" make test

# only push up tags
after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    VERSION="$TRAVIS_TAG" make release;
    fi
  - if [[ "$TRAVIS_TAG" == "$LATEST"* ]]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    VERSION="$TRAVIS_TAG" make tag_latest;
    VERSION="latest" make release_latest;
    fi
