#FROM selenium/base:3.3.1-arsenic
FROM registry.cn-hangzhou.aliyuncs.com/angle/abase:2.1
MAINTAINER Selenium <yangle@zs5s.com>


RUN apt-get update -qqy \
  && apt-get -qqy --no-install-recommends install \
    fonts-noto-cjk 
